apiVersion: v1
kind: Pod
metadata:
  name: client-allowed
  namespace: np-test
  labels:
    role: allowed
spec:
  containers:
    - name: client
      image: curlimages/curl:8.7.1
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: client-blocked
  namespace: np-test
  labels:
    role: blocked
spec:
  containers:
    - name: client
      image: curlimages/curl:8.7.1
      command: ["sleep", "3600"]
